import Beneficios from "@/components/home/beneficios";
import MasConexion from "@/components/home/masConexion";
import Recibiras from "@/components/home/recibiras";
import Somos from "@/components/home/somos";
import Ventajas from "@/components/home/ventajas";
import Workshop from "@/components/home/workshop";
import Head from "next/head";

function Home() {
   return (
      <div className="w-full flex flex-col items-center">
         <Head>
            <title>Forma lideres</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Workshop />
         <Somos />
         <Recibiras />
         <MasConexion />
         <Beneficios />
         <Ventajas />
      </div>
   );
}

export default Home;
